## defaults for _all_ profiles
[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
# remappings = []
libraries = []
cache = true
force = false
evm_version = 'london'
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
solc_version = '0.8.11'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = []
fuzz_runs = 500
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 0
chain_id = 1
gas_limit = 9_223_372_036_854_775_807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0


## !! Environment Variables !! ##

# Foundry's tools read all environment variable names prefixed with `FOUNDRY_` using the string after the `_` as the name
# of a configuration value as the value of the parameter as the value itself. But the
# corresponding [dapptools](https://github.com/dapphub/dapptools/tree/master/src/dapp#configuration) config vars are also
# supported, this means that `FOUNDRY_SRC` and `DAPP_SRC` are equivalent.

# Environment variables take precedence over values in `foundry.toml`. Values are parsed as loose form of TOML syntax.
# Consider the following examples: